In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
url = 'https://raw.githubusercontent.com/EdoHanifauzan/data/main/credit_score.csv'
data = pd.read_csv(url)

In [4]:
data.head

<bound method NDFrame.head of      Unnamed: 0 kode_kontrak  pendapatan_setahun_juta kpr_aktif  \
0             1   AGR-000001                      295        YA   
1             2   AGR-000011                      271        YA   
2             3   AGR-000030                      159     TIDAK   
3             4   AGR-000043                      210        YA   
4             5   AGR-000049                      165     TIDAK   
..          ...          ...                      ...       ...   
895         896   AGR-010739                      112        YA   
896         897   AGR-010744                      120        YA   
897         898   AGR-010758                      166     TIDAK   
898         899   AGR-010775                      196     TIDAK   
899         900   AGR-010790                      204     TIDAK   

     durasi_pinjaman_bulan  jumlah_tanggungan rata_rata_overdue  risk_rating  
0                       48                  5      61 - 90 days            4  
1      

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
ohe = OneHotEncoder()
transformed = ohe.fit_transform(data[['kpr_aktif']])
transformed.toarray()

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [6]:
transformer = make_column_transformer(
    (OneHotEncoder(), ['kpr_aktif', 'rata_rata_overdue']),
    remainder='passthrough')

transformed = transformer.fit_transform(data)
t_data = pd.DataFrame(
    transformed, 
    columns=transformer.get_feature_names()
)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [7]:
# x sebagai variable independent
X = t_data.drop(['risk_rating','kode_kontrak',], axis = 1) 
Y = data.iloc[:, -1].values

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
le = LabelEncoder()
Y = le.fit_transform(Y)

In [9]:
X

onehotencoder__x0_TIDAK onehotencoder__x0_YA  \
0                       0.0                  1.0   
1                       0.0                  1.0   
2                       1.0                  0.0   
3                       0.0                  1.0   
4                       1.0                  0.0   
..                      ...                  ...   
895                     0.0                  1.0   
896                     0.0                  1.0   
897                     1.0                  0.0   
898                     1.0                  0.0   
899                     1.0                  0.0   

    onehotencoder__x1_0 - 30 days onehotencoder__x1_31 - 45 days  \
0                             0.0                            0.0   
1                             0.0                            0.0   
2                             1.0                            0.0   
3                             0.0                            0.0   
4                             0.0                            1.0   
..                            ...                            ...   
895                           0.0                            0.0   
896                           0.0                            0.0   
897                           1.0                            0.0   
898                           0.0                            1.0   
899                           1.0                            0.0   

    onehotencoder__x1_46 - 60 days onehotencoder__x1_61 - 90 days  \
0                              0.0                            1.0   
1                              0.0                            1.0   
2                              0.0                            0.0   
3                              1.0                            0.0   
4                              0.0                            0.0   
..                             ...                            ...   
895                            0.0                            0.0   
896                            1.0                            0.0   
897                            0.0                            0.0   
898                            0.0                            0.0   
899                            0.0                            0.0   

    onehotencoder__x1_> 90 days Unnamed: 0 pendapatan_setahun_juta  \
0                           0.0          1                     295   
1                           0.0          2                     271   
2                           0.0          3                     159   
3                           0.0          4                     210   
4                           0.0          5                     165   
..                          ...        ...                     ...   
895                         1.0        896                     112   
896                         0.0        897                     120   
897                         0.0        898                     166   
898                         0.0        899                     196   
899                         0.0        900                     204   

    durasi_pinjaman_bulan jumlah_tanggungan  
0                      48                 5  
1                      36                 5  
2                      12                 0  
3                      12                 3  
4                      36                 0  
..                    ...               ...  
895                    48                 5  
896                    48                 2  
897                    24                 2  
898                    48                 0  
899                    24                 2  

[900 rows x 11 columns]

In [10]:
Y

array([3, 3, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 3, 3, 0, 0, 0, 2, 4, 2, 2, 4, 2, 4, 2, 0, 2, 0, 2,
       4, 0, 2, 2, 4, 0, 2, 3, 1, 2, 1, 0, 3, 2, 2, 2, 0, 3, 0, 3, 2, 0,
       2, 4, 2, 4, 4, 4, 2, 4, 2, 0, 4, 4, 2, 2, 0, 4, 0, 0, 1, 2, 2, 3,
       0, 3, 0, 2, 2, 2, 2, 0, 1, 1, 2, 3, 3, 2, 1, 0, 2, 2, 2, 2, 3, 3,
       0, 2, 0, 1, 2, 2, 2, 4, 1, 2, 4, 2, 0, 4, 4, 0, 4, 4, 2, 1, 4, 2,
       4, 0, 1, 2, 2, 4, 4, 2, 0, 0, 0, 2, 0, 0, 4, 0, 2, 4, 2, 1, 2, 2,
       0, 0, 0, 2, 4, 2, 4, 1, 2, 2, 2, 0, 4, 2, 2, 2, 0, 0, 1, 0, 4, 2,
       2, 4, 3, 2, 3, 4, 2, 2, 4, 0, 0, 2, 2, 1, 2, 0, 1, 2, 0, 2, 1, 1,
       1, 3, 2, 1, 2, 0, 1, 4, 4, 3, 2, 0, 1, 1, 4, 3, 4, 1, 2, 2, 0, 2,
       4, 0, 1, 4, 2, 0, 4, 2, 0, 3, 1, 0, 2, 2, 2,

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB()

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [16]:
cm

array([[69,  0,  0,  0,  0],
       [ 0, 49,  0,  0,  0],
       [ 0,  0, 84,  0,  0],
       [ 0,  0,  0, 36,  0],
       [ 0,  0,  0,  0, 32]])

In [17]:
from sklearn.metrics import classification_report
y_pred = classifier.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00        49
           2       1.00      1.00      1.00        84
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        32

    accuracy                           1.00       270
   macro avg       1.00      1.00      1.00       270
weighted avg       1.00      1.00      1.00       270



In [19]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, Y_train)

acc_knn = round(neigh.score(X_train, Y_train) * 100, 2)
print(acc_knn)

100.0
